// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

namespace backend.Migrations
{
    [DbContext(typeof(AgroContext))]
    [Migration("20201210133056_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("backend.Models.Imovel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.HasKey("Id")
                        .HasName("pk_imovel_car");

                    b.ToTable("imovel_car");
                });

            modelBuilder.Entity("backend.Models.Talhao", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("ImovelId")
                        .HasColumnType("integer")
                        .HasColumnName("imovel_id");

                    b.Property<string>("Nome")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero");

                    b.Property<Geometry>("TheGeom")
                        .HasColumnType("geometry")
                        .HasColumnName("the_geom");

                    b.HasKey("ID")
                        .HasName("pk_talhao");

                    b.HasIndex("ImovelId")
                        .HasDatabaseName("ix_talhao_imovel_id");

                    b.ToTable("talhao");
                });

            modelBuilder.Entity("backend.Models.Talhao", b =>
                {
                    b.HasOne("backend.Models.Imovel", "Imovel")
                        .WithMany("Talhoes")
                        .HasForeignKey("ImovelId")
                        .HasConstraintName("fk_talhao_imovel_car_imovel_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Imovel");
                });

            modelBuilder.Entity("backend.Models.Imovel", b =>
                {
                    b.Navigation("Talhoes");
                });
#pragma warning restore 612, 618
        }
    }
}
